name       : os-installer
version    : 16.1
release    : 125
source     :
    - git|https://github.com/getsolus/os-installer.git : ab4d9bae7597dd2345e0129d31ba02e7d0b9c178
homepage   : https://getsol.us
license    : GPL-2.0-only
summary    : Official installer of Solus
description: |
    Official installer of Solus
component  : system
builddeps  :
    - python-setuptools
rundeps    :
    - gsettings-desktop-schemas
    - libgnome-desktop
    - libtimezonemap
    - python-cairo
    - python-geoip
    - python-gobject
    - python-parted
    - setxkbmap
build      : |
    %python_setup
install    : |
    %python_install

    # Assets
    install -Dm00644 dist/org.freedesktop.policykit.pkexec.policy $installdir/usr/share/polkit-1/actions/org.freedesktop.policykit.pkexec.policy
    install -Dm00755 dist/os-installer-wrapper $installdir/usr/bin/os-installer-wrapper
    install -Dm00644 $pkgfiles/10-livecd.rules $installdir/usr/share/polkit-1/rules.d/10-livecd.rules
    install -Dm00644 dist/install-symbolic.svg $installdir/usr/share/icons/gnome/scalable/actions/install-symbolic.svg

    # Temporary! AppSystem borkage
    install -Dm00644 dist/com.solus_project.Installer.desktop $installdir/usr/share/applications/os-installer-gtk.desktop

    # Ensure GDM works again post-install
    install -Dm00644 $pkgfiles/custom.conf $installdir/usr/share/os-installer/custom.conf
